# generated by mBlock5 for CyberPi
# codes make you happy

import event, time, cyberpi, mbuild, mbot2
# initialize variables
ON_OFF = 0
Y_COUB_BOX = 0
_D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F = 0
R1 = 0
R2 = 0
G1 = 0
G2 = 0
B1 = 0
B2 = 0
_D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96 = 0
_D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B = 0
color1234 = 0
_D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96 = 0
_D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96 = 0
_D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96 = 0
G_COUB_BOX = 0
B_COUB_BOX = 0
R_COUB_BOX = 0
cyberpi.cloud_broadcast.start('{TOPIC}')

@cyberpi.event.cloud_broadcast('on')
def on_cloud_broadcast():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    ON_OFF = 1

@cyberpi.event.cloud_broadcast('off')
def on_cloud_broadcast1():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    ON_OFF = 0

@cyberpi.event.cloud_broadcast('ycoub1')
def on_cloud_broadcast2():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    Y_COUB_BOX = 1

@cyberpi.event.cloud_broadcast('ycoub2')
def on_cloud_broadcast3():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    Y_COUB_BOX = 2

@event.start
def on_start():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    cyberpi.wifi.connect('ALTECRU', '9874123654789')
    while not cyberpi.wifi.is_connect():
        pass

    cyberpi.led.play('rainbow')
    time.sleep(1)
    cyberpi.audio.play('start')
    cyberpi.led.off("all")
    ON_OFF = 0
    Y_COUB_BOX = 0
    G_COUB_BOX = 0
    B_COUB_BOX = 0
    R_COUB_BOX = 0
    color1234 = 0
    _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F = 0
    R1 = 0
    R2 = 0
    G1 = 0
    G2 = 0
    B1 = 0
    B2 = 0
    while True:
        if ON_OFF == 1:
            cyberpi.console.clear()
            cyberpi.display.show_label('O N ', 24, "center", index= 0)
            mbuild.ultrasonic2.set_bri(100, "all", 1)
            if mbuild.ultrasonic2.get(1) < 7:
                mbot2.EM_stop("EM1")
                _D0_9E_D0_BF_D1_80_D0_B5_D0_B4_D0_B5_D0_BB_D0_B5_D0_BD_D0_B8_D0_B5__D1_86_D0_B2_D0_B5_D1_82_D0_B0()
                _D0_91_D0_BB_D0_BE_D0_BA__D0_B2_D1_8B_D0_B1_D0_BE_D1_80_D0_B0__D0_B4_D0_B5_D0_B9_D1_81_D1_82_D0_B2_D0_B8_D1_8F__D0_B4_D0_BB_D1_8F__D0_96_D0_95_D0_9B_D0_A2_D0_9E_D0_93_D0_9E__D0_9A_D0_A3_D0_91_D0_90()

            else:
                mbot2.EM_set_speed(40,"EM1")

        else:
            mbot2.EM_stop("ALL")
            mbuild.ultrasonic2.set_bri(0, "all", 1)

        cyberpi.console.set_font(16)
        cyberpi.console.print('Y_COUB -->')
        cyberpi.console.println(Y_COUB_BOX)
        cyberpi.console.print('G_COUB-->')
        cyberpi.console.println('0')
        cyberpi.display.show_label('O F F', 24, "bottom_right", index= 0)
        time.sleep(2)
        mbot2.EM_stop("ALL")
        cyberpi.console.clear()
        cyberpi.display.show_label('O F F', 24, "bottom_right", index= 0)
        cyberpi.led.off("all")

def Print_RGB ():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    cyberpi.console.set_font(16)
    cyberpi.console.print('R1 ')
    cyberpi.console.print(mbuild.quad_rgb_sensor.get_red("R1",1))
    cyberpi.console.print(' R2 ')
    cyberpi.console.println(mbuild.quad_rgb_sensor.get_red("L1",1))
    cyberpi.console.print('G1 ')
    cyberpi.console.print(mbuild.quad_rgb_sensor.get_green("R1",1))
    cyberpi.console.print(' G2 ')
    cyberpi.console.println(mbuild.quad_rgb_sensor.get_green("L1",1))
    cyberpi.console.print('B1 ')
    cyberpi.console.print(mbuild.quad_rgb_sensor.get_blue("R1",1))
    cyberpi.console.print(' B2 ')
    cyberpi.console.println(mbuild.quad_rgb_sensor.get_blue("L1",1))
    cyberpi.console.print('Dist ')
    cyberpi.console.print(mbuild.ultrasonic2.get(1))
    cyberpi.console.print(' cm')
    time.sleep(3)
    cyberpi.console.clear()

def Print_data ():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    cyberpi.console.print('on/off_')
    cyberpi.console.println(ON_OFF)
    cyberpi.console.print('dist_')
    cyberpi.console.println(mbuild.ultrasonic2.get(1))
    cyberpi.console.print('Y_coub_box ')
    cyberpi.console.println(Y_COUB_BOX)
    cyberpi.console.print('colour1234_')
    cyberpi.console.println(color1234)
    time.sleep(0.1)
    cyberpi.console.clear()

def _D0_91_D0_BB_D0_BE_D0_BA__D0_B2_D1_8B_D0_B1_D0_BE_D1_80_D0_B0__D0_B4_D0_B5_D0_B9_D1_81_D1_82_D0_B2_D0_B8_D1_8F__D0_B4_D0_BB_D1_8F__D0_96_D0_95_D0_9B_D0_A2_D0_9E_D0_93_D0_9E__D0_9A_D0_A3_D0_91_D0_90 ():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    if Y_COUB_BOX == 1 and color1234 == 1:
        mbot2.EM_turn(360, 50, "EM2")

    if Y_COUB_BOX == 2 and color1234 == 1:
        mbot2.EM_turn(360, 50, "EM2")

def _D0_9E_D0_BF_D1_80_D0_B5_D0_B4_D0_B5_D0_BB_D0_B5_D0_BD_D0_B8_D0_B5__D1_86_D0_B2_D0_B5_D1_82_D0_B0 ():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F = mbuild.ultrasonic2.get(1)
    R1 = mbuild.quad_rgb_sensor.get_red("R1",1)
    R2 = mbuild.quad_rgb_sensor.get_red("L1",1)
    G1 = mbuild.quad_rgb_sensor.get_green("R1",1)
    G2 = mbuild.quad_rgb_sensor.get_green("L1",1)
    B1 = mbuild.quad_rgb_sensor.get_blue("R1",1)
    B2 = mbuild.quad_rgb_sensor.get_blue("L1",1)
    time.sleep(0.1)
    if R1 > 240 and G1 > 240 and B1 < 150:
        color1234 = 1
        cyberpi.led.show('black black yellow black black')
        time.sleep(0.1)

    else:
        if R1 > 240 and G1 < 150 and B1 < 150:
            color1234 = 2
            cyberpi.led.show('black black red black black')
            time.sleep(0.1)

        else:
            if R1 < 90 and G1 > 240 and B1 > 240:
                color1234 = 3
                cyberpi.led.show('black black blue black black')
                time.sleep(0.1)

            else:
                if R1 < 170 and G1 > 240 and B1 < 200:
                    color1234 = 4
                    cyberpi.led.show('black black green black black')
                    time.sleep(0.1)

                else:
                    color1234 = 0
                    cyberpi.led.off("all")

def _D0_9E_D1_82_D0_BF_D1_80_D0_B0_D0_B2_D0_BA_D0_B0__D0_B7_D0_BD_D0_B0_D1_87_D0_B5_D0_BD_D0_B8_D0_B9__D0_BF_D0_B5_D1_80_D0_B5_D0_BC_D0_B5_D0_BD_D0_BD_D1_8B_D1_85__D0_BD_D0_B0__D1_8D_D0_BA_D1_80_D0_B0_D0_BD ():
    global ON_OFF, Y_COUB_BOX, _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F, R1, R2, G1, G2, B1, B2, _D0_96_D0_B5_D0_BB_D1_82_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_92_D0_9A_D0_9B__D0_92_D0_AB_D0_9A_D0_9B, color1234, _D0_97_D0_B5_D0_BB_D0_B5_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, _D0_A1_D0_B8_D0_BD_D0_B8_D0_B9__D0_9A_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA__E2_84_96, _D0_9A_D1_80_D0_B0_D1_81_D0_BD_D1_8B_D0_B9__D0_BA_D1_83_D0_B1___D0_AF_D1_89_D0_B8_D0_BA_E2_84_96, G_COUB_BOX, B_COUB_BOX, R_COUB_BOX
    cyberpi.upload_broadcast.set('dist', _D0_B4_D0_B8_D1_81_D1_82_D0_B0_D0_BD_D1_86_D0_B8_D1_8F)
    cyberpi.upload_broadcast.set('R1', R1)
    cyberpi.upload_broadcast.set('R2', R2)
    cyberpi.upload_broadcast.set('G1', G1)
    cyberpi.upload_broadcast.set('G2', G2)
    cyberpi.upload_broadcast.set('B1', B1)
    cyberpi.upload_broadcast.set('B2', B2)

